package model.spem.util;

public enum IntegerDistributionEnum {
	BINOMIAL_DISTRIBUTION, GEOMETRIC_DISTRIBUTION, 
	PASCAL_DISTRIBUTION, POISSON_DISTRIBUTION, 
	UNIFORM_INTEGER_DISTRIBUTION, ZIP_DISTRIBUTION;
}
